root = "."
tmp_dir = "tmp"

[build]
  poll = true
  cmd = "go build -o tmp/agent ./cmd/agent/agent.go"
  bin = "tmp/agent"
  delay = 1000
  exclude_dir = ["assets", "tmp", "vendor", "internal/config"]
  include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
  exclude_regex = ["_test\\.go"]