FROM golang:1.23.10-alpine3.22 AS builder

RUN apk add --no-cache git

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN go build -o controlplane ./cmd/controlplane

FROM alpine:latest

WORKDIR /app

COPY --from=builder /app/controlplane .

EXPOSE 3344

ENTRYPOINT ["./controlplane"]
