version: "3.8"

services:

  # NGINX reverso (porta 80 do host)
  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
    ports:
      - "80:80"
    depends_on:
      - traefik

  # Traefik proxy dinâmico
  traefik:
    image: traefik:v2.10
    ports:
      - "8080:8080" # Painel Traefik
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik:/etc/traefik

  # App BLUE
  blue:
    image: nginx:alpine
    volumes:
      - ./html/blue:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.blue.loadbalancer.server.port=80"

  # App GREEN
  green:
    image: nginx:alpine
    volumes:
      - ./html/green:/usr/share/nginx/html:ro
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.green.loadbalancer.server.port=80"
