http:
  routers:
    app:
      rule: "Host(`localhost`)"
      service: blue-green-weighted
      entryPoints:
        - web

    dashboard:
      rule: "PathPrefix(`/dashboard`)"
      service: api@internal
      entryPoints:
        - traefik

    dashboard-api:
      rule: "PathPrefix(`/api`)"
      service: api@internal
      entryPoints:
        - traefik

  services:
    blue-green-weighted:
      weighted:
        services:
          - name: example-api@docker
            weight: 1
