api:
  dashboard: true

entryPoints:
  web:
    address: ":80"

  traefik:
    address: ":8080"

providers:
  docker:
    exposedByDefault: false
  file:
    directory: /etc/traefik/dynamic
    watch: true
